/**
 * Generated by KissMDA - Simple Java Cartridge - kissmda-cartridges-simple-java.
 * KissMDA: http://kissmda.org
 * <p>
 * DO NOT EDIT this file manually! All changes will be overwritten by next generation!
 * <p>
 * Generation date: Tue May 15 23:27:36 CEST 2018.
 */
package de.di.client;

import java.util.Set;

public interface SolutionService {
    Set<String> getSolutionUsers();
}
