/** 
 * Generated by KissMDA - Simple Java Cartridge - kissmda-cartridges-simple-java.
 * KissMDA: http://kissmda.org
 *  
 * DO NOT EDIT this file manually! All changes will be overwritten by next generation!
 *  
 * Generation date: Thu Sep 19 23:58:10 CEST 2019.
 */
package de.di;

public interface UdmService {

	String findUdmUserById(Long id);

}
